theme: jekyll-theme-cayman
title: YOUNG-HYUN SEO
description: School of Civil, Environmental and Architectural Engineering. Korea University

urls:
  - text: ABOUT
    url: /about
  - text: RESEARCH
    url: /research